### ISSUE TITLE
Load .json error: Cannot detach script

### ISSUE THREAD

**Issue by swc** [tts-community/moonsharp-tts-debug#3]
I get the following error after replacing MoonSharp.Interpreter.dll:

"Load .json error: Cannot detach script that is not attached to this debug server."

This error prevents me from loading a mod if it's not the first mod I've loaded since starting TTS. This forces me to restart TTS between each mod.

I enabled logging and didn't see any further details. Thanks!

tts-community/moonsharp release 2.0.0.0 (TTS Enhanced rev 5)
Tabletop Simulator v12.3.5
Windows 10 Home, up to date

**Comment by dlardo** [comment]
I'm getting the same thing. It can happen when I "save and play" from VSCode too.

**Comment by Benjamin-Dobell** [comment]
I believe this was resolved in Rev 6, mind you it introduced other bugs 🤷‍♂️

I would like to _properly_ revisit debugging in the near future. If you haven't already you'll want to upvote https://tabletopsimulator.nolt.io/34
